# Generated by Django 2.2.17 on 2020-12-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_auto_20201207_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadpenduduk',
            name='keluarga',
        ),
    ]
