# Generated by Django 2.2.17 on 2020-12-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_remove_sadpenduduk_keluarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadpenduduk',
            name='keluarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anggota', to='v1.SadKeluarga'),
        ),
    ]
