# Generated by Django 2.2.17 on 2020-12-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_sadpenduduk_keluarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigdesa',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sigdusun',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sigdesa',
            name='nama_desa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sigdusun',
            name='nama_dusun',
            field=models.CharField(max_length=70),
        ),
    ]
