# Generated by Django 2.2.17 on 2021-03-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20210313_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadpenduduk',
            name='no_hp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
