# Generated by Django 2.2.17 on 2021-04-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_sigrawanbencana'),
    ]

    operations = [
        migrations.AddField(
            model_name='saddesa',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='youtube',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
