# Generated by Django 2.2.17 on 2021-04-14 04:21

import api_sad_sig.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20210410_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='saddesa',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination),
        ),
    ]
