# Generated by Django 2.2.17 on 2021-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20210415_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadpenduduk',
            name='golongan_darah',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
