# Generated by Django 2.2.17 on 2021-04-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20210415_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='potensi',
            name='luas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='potensi',
            name='pemanfaatan_tanah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensi',
            name='penggunaan_tanah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensi',
            name='rtrw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensi',
            name='status_hak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
