# Generated by Django 2.2.17 on 2021-01-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0065_auto_20210107_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='ayah',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='ibu',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='pegawai',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='saksi1',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='saksi2',
        ),
        migrations.RemoveField(
            model_name='suratkelahiran',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='suratskck',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suratskck',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='suratskck',
            name='pegawai',
        ),
        migrations.RemoveField(
            model_name='suratskck',
            name='penduduk',
        ),
        migrations.RemoveField(
            model_name='suratskck',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SuratDomisili',
        ),
        migrations.DeleteModel(
            name='SuratKelahiran',
        ),
        migrations.DeleteModel(
            name='SuratSkck',
        ),
    ]
